"""
Landing Page Example - KD UI Framework
Demonstrates the landing page components generated by the MCP server
"""

from flask import Flask

app = Flask(__name__)

# Import the landing page generator
import sys
sys.path.insert(0, '../../mcp-server/src')
from kd_ui_server.tools.landing_page import create_landing_page


@app.route('/')
def index():
    """Main landing page route"""
    # Generate the complete landing page using the MCP tool
    html = create_landing_page(
        title="KD UI Framework - Beautiful UI Components for Flask",
        company_name="KD UI Framework"
    )
    return html


if __name__ == '__main__':
    print("\n" + "="*50)
    print("🎨 KD UI Framework - Landing Page Example")
    print("="*50)
    print("\n🚀 Starting Flask server...")
    print("📊 Landing page available at: http://localhost:5002")
    print("\nPress Ctrl+C to stop\n")
    app.run(debug=True, port=5002)
